#!/bin/bash

# Railway Multi-Service Setup Script
echo "🚀 Setting up Firecrawl as individual Railway services..."
echo "======================================================"
echo ""

echo "❌ STEP 1: Delete the failing service"
echo "Go to your Railway project dashboard and delete the failing service that's trying to use Nixpacks"
echo "Project: https://railway.com/project/f4cba472-90a4-414d-90c5-657e13b78c7a"
echo ""
read -p "Press Enter after deleting the failing service..."

echo ""
echo "🗄️ STEP 2: Add Redis Database"
echo "1. Click 'New Service' → 'Database' → 'Add Redis'"
echo "2. Name it: 'firecrawl-redis'"
echo "3. Railway will auto-generate REDIS_URL"
echo ""
read -p "Press Enter after adding Redis service..."

echo ""
echo "🎭 STEP 3: Add Playwright Service"
echo "1. Click 'New Service' → 'GitHub Repo'"
echo "2. Select: 'Boetie78/firecrawl-railway-selfhosted'"
echo "3. Service Name: 'playwright-service'"
echo "4. Root Directory: 'apps/playwright-service-ts'"
echo "5. Railway will auto-detect Node.js"
echo ""
read -p "Press Enter after adding Playwright service..."

echo ""
echo "🔥 STEP 4: Add API Service"
echo "1. Click 'New Service' → 'GitHub Repo'"
echo "2. Select: 'Boetie78/firecrawl-railway-selfhosted'"
echo "3. Service Name: 'firecrawl-api'"
echo "4. Root Directory: 'apps/api'"
echo "5. Railway will auto-detect Node.js"
echo ""
read -p "Press Enter after adding API service..."

echo ""
echo "👷 STEP 5: Add Worker Service"
echo "1. Click 'New Service' → 'GitHub Repo'"
echo "2. Select: 'Boetie78/firecrawl-railway-selfhosted'"
echo "3. Service Name: 'firecrawl-worker'"
echo "4. Root Directory: 'apps/api'"
echo "5. Add Environment Variable: START_COMMAND='pnpm run workers'"
echo ""
read -p "Press Enter after adding Worker service..."

echo ""
echo "⚙️ STEP 6: Configure Environment Variables"
echo ""
echo "For 'firecrawl-api' service, add these environment variables:"
echo "PORT=3002"
echo "HOST=0.0.0.0"
echo "USE_DB_AUTHENTICATION=false"
echo "BULL_AUTH_KEY=firecrawl-railway-2024"
echo "REDIS_URL=\${{firecrawl-redis.REDIS_URL}}"
echo "REDIS_RATE_LIMIT_URL=\${{firecrawl-redis.REDIS_URL}}"
echo "PLAYWRIGHT_MICROSERVICE_URL=https://\${{playwright-service.RAILWAY_PUBLIC_DOMAIN}}/scrape"
echo ""
read -p "Press Enter after configuring API environment variables..."

echo ""
echo "For 'firecrawl-worker' service, add these environment variables:"
echo "USE_DB_AUTHENTICATION=false"
echo "REDIS_URL=\${{firecrawl-redis.REDIS_URL}}"
echo "REDIS_RATE_LIMIT_URL=\${{firecrawl-redis.REDIS_URL}}"
echo "PLAYWRIGHT_MICROSERVICE_URL=https://\${{playwright-service.RAILWAY_PUBLIC_DOMAIN}}/scrape"
echo ""
read -p "Press Enter after configuring Worker environment variables..."

echo ""
echo "For 'playwright-service', add this environment variable:"
echo "PORT=3000"
echo ""
read -p "Press Enter after configuring Playwright environment variables..."

echo ""
echo "🎉 DEPLOYMENT COMPLETE!"
echo ""
echo "Your services should now be deploying. Monitor the Railway dashboard."
echo ""
echo "Once all services are running (green status):"
echo "1. Get your API URL from the 'firecrawl-api' service"
echo "2. Test with: ./test-firecrawl.sh YOUR_API_URL"
echo "3. Access admin panel at: YOUR_API_URL/admin/firecrawl-railway-2024/queues"
echo ""
echo "✅ All services should be running within 5-10 minutes!"
